# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e9392c178e1671e408f43ac0a551cc6187603a4ab5c835dd1eaad1a685ab3c14d10fb2df3eadfe14c89acc2593debfe16b1f381b5d19d5be5ff7e2bb68358d

test:
  secret_key_base: 7b6144ead38d0f528f09071748091b29029f735dac79cda7064dcaa80402b297d39896bd445b1e70783bf8aed733d5d9206711f63dbe6577a42a53f5a85ec146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
